### PR TITLE
fix multiline strings bug

### LINKED ISSUE #1: Multiline strings are not supported
Hi, please see this as an example: https://raw.githubusercontent.com/toml-lang/toml/master/examples/example-v0.4.0.toml

``` toml
[string.literal.multiline]

regex2 = '''I [dw]on't need \d{2} apples'''
lines  = '''
The first newline is
trimmed in raw strings.
   All other whitespace
   is preserved.
'''
```

### PR DESCRIPTION
**Pull request by swr1bm86**
Fix #1 

cause in the original lexer just use `.` to match content insides the multiline string, so it will never match the end of it.

reference the [python docstring lexer](https://github.com/JetBrains/intellij-community/blob/master/python/src/com/jetbrains/python/lexer/Python.flex#L67-L70) in intellij-community to fix this.

it's looks fine now. Cheers!

@matklad

### CODE REVIEW

**Comment by matklad** [comment]
Thanks!

I think there is a bit more work to be done here:
- Tests (you can add them [here](https://github.com/intellij-rust/intellij-toml/blob/master/src/test/resources/org/toml/lang/core/parser/fixtures/well-formed/example.toml))
- I think rules for single quoted and double quoted string should look similar. It is possible that current rule for double quoted string is wrong (and this implies that some tests are also missig). 
- Can you add here support for single line literal strings? (`'C:\Users\nodejs\templates'`)

**Comment by matklad** [comment]
You should be able to get good tests from here: https://github.com/BurntSushi/toml-test

**Comment by swr1bm86** [comment]
cool, i will work on this! and btw single line literal strings is already supported.

**Comment by swr1bm86** [comment]
why is [this](https://github.com/BurntSushi/toml-test/blob/master/tests/valid/string-escapes.toml#L1) valid and [this](https://github.com/BurntSushi/toml-test/blob/master/tests/invalid/string-bad-escape.toml#L1) invalid? @matklad

**Comment by matklad** [comment]
Because

> All other escape sequences not listed above are reserved and, if used, TOML should produce an error.

https://github.com/toml-lang/toml#string

**Comment by swr1bm86** [comment]
ok, get it. thx :)

**Comment by andyfleming** [comment]
What's still missing here?

**Comment by matklad** [comment]
> What's still missing here?

The main thing that's missing is tests

**Comment by swr1bm86** [comment]
@matklad i'll wrap this up soon 😂  this PR is pending for a long time .

**Comment by swr1bm86** [comment]
@matklad tests added.

**Comment by matklad** [comment]
Thanks!

**Pull request merged**
