### PR TITLE
Make the plugin buildable

### PR DESCRIPTION
**Pull request by dlsniper**
The plugin now compiles with IDEA 16 EAP (144) branch.
It also supports the Kotlin RC1 release.

This PR also makes the whole plugin buildable as there are
many issues with the included `build.gradle` file.

### CODE REVIEW

**Comment by dlsniper** [comment]
I already have a CLA signed with JetBrains, in case this is needed for the project.

**Comment by matklad** [comment]
looks like the build was fixed in https://github.com/intellij-rust/intellij-toml/commit/20f655782626a02052971d87ff3ecfd6f01a8787

**Comment by matklad** [comment]
at least partialy. This still uses an old version of Kotlin

**Comment by dlsniper** [comment]
not sure about this, I'll have to check to see how it behaves in a non-JB system, will do tonight, thanks for the update.

**Comment by matklad** [comment]
Closed due to inactivity

**Comment by alexeykudinkin** [comment]
It should be build-able by its own, since decouple.

**Comment by alexeykudinkin** [comment]
Would check this tonight.

**Comment by dlsniper** [comment]
I've dropped the ball on this one, sorry.

**Pull request closed without merging**
